[project]
name = "knowflow"
version = "0.1.0"
description = "A Knowledge-Driven RAG System for Enterprise Q&A"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "pydantic-settings>=2.10.1",
    "uvicorn>=0.35.0",
]
