FROM neo4j:5.15.0

ENV NEO4J_AUTH=neo4j/Pstm!tr0ae#123
ENV NEO4J_PLUGINS=["apoc"]
ENV NEO4J_dbms_security_procedures_unrestricted=apoc.*
ENV NEO4J_dbms_default__listen__address=0.0.0.0
ENV NEO4J_dbms_memory_heap_initial__size=512m
ENV NEO4J_dbms_memory_heap_max__size=2G

RUN mkdir -p /data /logs /var/lib/neo4j/import /plugins

EXPOSE 7687

VOLUME ["/data", "/logs", "/var/lib/neo4j/import", "/plugins"]
